### ISSUE TITLE
Sending/receiving button is overlapping with currently selected country

### ISSUE THREAD

**Issue by daanlouter** [level73/cfa-bubble-network#3]
When a country is selected, the text for that country is overlaying the Sending/Receiving buttons.

I also just noticed that when clicking on Sending/Receiving while in “selected”-mode, it will just go to the main view again. So maybe best to just hide the buttons altogether when a country is selected?

<img width="369" alt="Screenshot 2019-03-28 at 09 47 56" src="https://user-images.githubusercontent.com/3636117/56580887-a60ac180-65cb-11e9-90d9-53e24303fec7.png">

**Comment by IronRunes** [comment]
hey @daanlouter I cannot replicate this issue. Am i correct to assume that this is happening on portrait mobile view?

**Comment by daanlouter** [comment]
Hey @IronRunes it still seems to happen to me:

![May-16-2019 14-16-56](https://user-images.githubusercontent.com/3636117/57856718-7d9a6f80-77e5-11e9-9b46-4883a579793e.gif)

I just compared to an older version of the template, and it does look fine there. So it's possible I introduced this bug. I'll assign issue to me and will take a look this week 🙂

**Comment by daanlouter** [comment]
This was fixed in the CFA fork: https://github.com/CodeForAfrica/bubble-network-flourish/commit/78d75a0c67ec98175b33ecfabb5126942a4f190b
